spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create # entity 와 매핑되는 테이블을 데이터베이스에 자동으로 생성
    properties:
      hibernate:
        show_sql: true  # JPA AIP를 통해 실행되는 SQL 쿼리를 로그로 출력
        format_sql: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

